DROP DATABASE IF EXISTS fitness;
CREATE DATABASE fitness;

\c fitness;

CREATE TABLE Chest (
  ID SERIAL PRIMARY KEY,
  EXERCISE VARCHAR,
  PICTURE VARCHAR,
  VIDEO VARCHAR,
  TYPE VARCHAR
);
CREATE TABLE Shoulders (
  ID SERIAL PRIMARY KEY,
  EXERCISE VARCHAR,
  PICTURE VARCHAR,
  VIDEO VARCHAR,
  TYPE VARCHAR
);
CREATE TABLE Legs (
  ID SERIAL PRIMARY KEY,
  EXERCISE VARCHAR,
  PICTURE VARCHAR,
  VIDEO VARCHAR,
  TYPE VARCHAR
);
CREATE TABLE Back (
  ID SERIAL PRIMARY KEY,
  EXERCISE VARCHAR,
  PICTURE VARCHAR,
  VIDEO VARCHAR,
  TYPE VARCHAR
);
CREATE TABLE Biceps (
  ID SERIAL PRIMARY KEY,
  EXERCISE VARCHAR,
  PICTURE VARCHAR,
  VIDEO VARCHAR,
  TYPE VARCHAR
);
CREATE TABLE Triceps (
  ID SERIAL PRIMARY KEY,
  EXERCISE VARCHAR,
  PICTURE VARCHAR,
  VIDEO VARCHAR,
  TYPE VARCHAR
);
CREATE TABLE Abs (
  ID SERIAL PRIMARY KEY,
  EXERCISE VARCHAR,
  PICTURE VARCHAR,
  VIDEO VARCHAR
);

\COPY Chest (EXERCISE, PICTURE, VIDEO, TYPE) FROM '/Users/stevenlee/Github/fit.ly/data/Chest.csv' WITH DELIMITER AS ',' CSV HEADER;
\COPY Shoulders (EXERCISE, PICTURE, VIDEO, TYPE) FROM '/Users/stevenlee/Github/fit.ly/data/Shoulders.csv' WITH DELIMITER AS ',' CSV HEADER;
\COPY Legs (EXERCISE, PICTURE, VIDEO, TYPE) FROM '/Users/stevenlee/Github/fit.ly/data/Legs.csv' WITH DELIMITER AS ',' CSV HEADER;
\COPY Back (EXERCISE, PICTURE, VIDEO, TYPE) FROM '/Users/stevenlee/Github/fit.ly/data/Back.csv' WITH DELIMITER AS ',' CSV HEADER;
\COPY Biceps (EXERCISE, PICTURE, VIDEO, TYPE) FROM '/Users/stevenlee/Github/fit.ly/data/Biceps.csv' WITH DELIMITER AS ',' CSV HEADER;
\COPY Triceps (EXERCISE, PICTURE, VIDEO, TYPE) FROM '/Users/stevenlee/Github/fit.ly/data/Triceps.csv' WITH DELIMITER AS ',' CSV HEADER;
\COPY Abs (EXERCISE, PICTURE, VIDEO) FROM '/Users/stevenlee/Github/fit.ly/data/Abs.csv' WITH DELIMITER AS ',' CSV HEADER;
